services:
  - type: web
    name: hesh-automation
    env: node
    buildCommand: |
      npm install
      npx playwright install chromium
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: LOGIN_EMAIL
        sync: false
      - key: LOGIN_PASSWORD
        sync: false
